# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: RAIN200L-Z_PRENET_L1
model_type: PRENetModel
scale: 1
num_gpu: [1]  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: RAIN200L
    type: PairedImageDataset
    dataroot_gt: /data/dateset/rain200/RAIN200L/train/ground_truth.lmdb
    dataroot_lq: /data/dateset/rain200/RAIN200L/train/rainy_image.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 128
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: RAIN200L
    type: PairedImageDataset
    dataroot_gt: ~
    dataroot_lq: ~
    io_backend:
      type: disk

# network structures
network_g:
  type: Z_PRENet



# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: 0 # no warm up 10000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 0.5
    reduction: mean
#    toY: true

# validation settings
val:
#  val_freq: 10
#  val_freq: !!float 2.5e4
  val_freq: !!float 2e3
  save_img: false
  grids: false
  crop_size: 256
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 1
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
